### LOL Analysis

In [2]:
import numpy as np
import pandas as pd
import plotly as plt
#import necessary libaries

In [12]:
lol = pd.read_csv('ALL_REGIONS.CSV')
#reading csv

In [7]:
lol.head()
#getting top 5 players

,Unnamed: 0,summonerId,summonerName,leaguePoints,rank,region,championId,mainChampion,championType
0,0,eUAem_YIulMFpQ4OE8YGfmFi5hMrLOu5ZausZgzvXHFRXu8,Nick link,1873,I,BR1,24,Jax,Fighter
1,1,9AJ5yvWsinzJtQzDgTUCEbuxOUsRlwKmSGOIipaVJaQ6xX...,hidanvs1,1812,I,BR1,126,Jayce,Fighter
2,2,KuUrlLtNgu0rHFekube8sOVtowEKoK4bKGfnsif0WKWEGw,Morttheusz,1786,I,BR1,81,Ezreal,Marksman
3,3,ckewCLrxG1msVOxaGN0mXykk-v66iOiq5U33GkTxzM5kHw,QUINDINHO,1719,I,BR1,55,Katarina,Assassin
4,4,UoG1L5AHUuiDc9dBCFKIH4nCVnvjRVED63pYLAkrk4ze,SSG Corëjj,1663,I,BR1,888,Renata,Support

In [26]:
lol.drop(['summonerId'], axis=1)

# vanishing unecessary column

,Unnamed: 0,summonerName,leaguePoints,rank,region,championId,mainChampion,championType
0,0,Nick link,1873,I,BR1,24,Jax,Fighter
1,1,hidanvs1,1812,I,BR1,126,Jayce,Fighter
2,2,Morttheusz,1786,I,BR1,81,Ezreal,Marksman
3,3,QUINDINHO,1719,I,BR1,55,Katarina,Assassin
4,4,SSG Corëjj,1663,I,BR1,888,Renata,Support
...,...,...,...,...,...,...,...,...
1988,1988,Trertas,503,I,TR1,157,Yasuo,Fighter
1989,1989,PSYÐUCK,502,I,TR1,55,Katarina,Assassin
1990,1990,ğ1ğ1ğ1ğ1ğ1ğ1ğ1ğ1,502,I,TR1,9,Fiddlesticks,Mage
1991,1991,Snophén,501,I,TR1,267,Nami,Support
1992,1992,Expecto Patrounm,494,I,TR1,53,Blitzcrank,Tank

In [23]:
lol.info()
#getting basic info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1993 entries, 0 to 1992
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    1993 non-null   int64
 1   summonerId    1993 non-null   object
 2   summonerName  1993 non-null   object
 3   leaguePoints  1993 non-null   int64
 4   rank          1993 non-null   object
 5   region        1993 non-null   object
 6   championId    1993 non-null   int64
 7   mainChampion  1993 non-null   object
 8   championType  1993 non-null   object
dtypes: int64(3), object(6)
memory usage: 140.3+ KB

In [24]:
lol.describe()
#geral stats

        Unnamed: 0  leaguePoints   championId
count  1993.000000   1993.000000  1993.000000
mean    996.000000    896.644255   154.797792
std     575.473863    220.980753   152.050525
min       0.000000    462.000000     1.000000
25%     498.000000    774.000000    64.000000
50%     996.000000    875.000000   104.000000
75%    1494.000000   1015.000000   166.000000
max    1992.000000   1873.000000   888.000000